In [7]:
import numpy as np

# ============================================================
# BROADCASTING
# ============================================================
# Broadcasting = Different-shaped arrays ni NumPy automatically
# adjust chesi element-wise operation cheyyadam.
#
# RULE:
# Compare shapes from RIGHT -> LEFT
#
# Two dimensions are compatible when:
#   1. They are equal
#   2. OR one of them is 1
#
# If dimensions are different AND neither is 1 -> ❌ Error
# ============================================================


# ------------------------------------------------------------
# 1. Scalar Broadcasting
# ------------------------------------------------------------
# Scalar = single value
# NumPy applies 10 to EVERY element

arr = np.array([1, 2, 3])

print("Scalar Broadcasting:")
print(arr + 10)
# [11 12 13]



Scalar Broadcasting:
[11 12 13]


In [8]:

# ------------------------------------------------------------
# 2. Broadcasting with 2D Array
# ------------------------------------------------------------
# Shape of matrix = (2, 3)
# Shape of vector = (3,)
#
# NumPy treats vector conceptually like:
# [10, 20, 30]
# [10, 20, 30]
#
# Then addition happens element-wise.

matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

vector = np.array([10, 20, 30])

print("\n2D + 1D Broadcasting:")
print(matrix + vector)





2D + 1D Broadcasting:
[[11 22 33]
 [14 25 36]]


In [9]:
# ------------------------------------------------------------
# 3. Broadcasting Rules Example
# ------------------------------------------------------------

# (2, 3)
# (1, 3)
#
# Compare RIGHT -> LEFT:
#
# 3 vs 3  -> same ✅
# 2 vs 1  -> one is 1 ✅
#
# Therefore broadcasting works.

a = np.ones((2, 3))
b = np.ones((1, 3))

print("\nCompatible Shapes:")
print("a shape:", a.shape)
print("b shape:", b.shape)
print(a + b)





Compatible Shapes:
a shape: (2, 3)
b shape: (1, 3)
[[2. 2. 2.]
 [2. 2. 2.]]


In [10]:
# ------------------------------------------------------------
# 4. Row Vector + Column Vector
# ------------------------------------------------------------
# (1, 4) × (4, 1)
#
# RIGHT -> LEFT:
#
# 4 vs 1 -> one is 1 ✅
# 1 vs 4 -> one is 1 ✅
#
# Therefore result becomes (4, 4).
#
# This can create a multiplication table.

row = np.array([[1, 2, 3, 4]])       # shape (1, 4)
column = np.array([[1], [2], [3], [4]])  # shape (4, 1)

print("\nRow × Column Broadcasting:")
print(row * column)





Row × Column Broadcasting:
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


In [11]:
# ------------------------------------------------------------
# 5. Incompatible Shapes
# ------------------------------------------------------------
# (2, 4)
# (4, 1)
#
# RIGHT -> LEFT:
#
# 4 vs 1 -> one is 1 ✅
# 2 vs 4 -> different ❌ and neither is 1
#
# Therefore broadcasting is NOT possible.
#
# Uncomment to see the ValueError:
#
# x = np.ones((2, 4))
# y = np.ones((4, 1))
# print(x + y)


# ============================================================
# QUICK REVISION
# ============================================================
# Broadcasting:
#
# RIGHT -> LEFT
#
# Same → ✅
# One is 1 → ✅
# Different + neither is 1 → ❌
#
# Example:
# (2, 3) + (1, 3) → ✅
# (2, 3) + (3, 1) → ❌
# (2, 4) + (4, 1) → ❌
# (1, 4) * (4, 1) → ✅ → result (4, 4)
# ============================================================