In [1]:
pip install numpy

In [3]:
import numpy as np

In [7]:
#Arrays
#Creating an array in numpy
array=np.array([1,2,3,4])
print(type(array))

<class 'numpy.ndarray'>


In [19]:
#scalar operation on array
s=array*2 #multiples each element by 2
print(s)
t=array+1 # increment each element by 1
print(t)
u=array-2 #decrement each element by 2
print(u)
v=array/4 #float division
print(v)
array//4  #interger division

[2 4 6 8]
[2 3 4 5]
[-1  0  1  2]
[0.25 0.5  0.75 1.  ]


array([0, 0, 0, 1])

In [22]:
#duplicating the array
arr=np.array([1,2,3,4])
print([1,2,3,4]*2 )#duplciates the element rather than multiplying
[1,2,3,4]*3

[1, 2, 3, 4, 1, 2, 3, 4]


[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

In [24]:
arr = np.array([10, 20, 30])
# dtype for the data type of the array
print(arr.dtype)

int64


In [25]:
#dimensions
#ndim reports number of dimensions


In [26]:


# 1D Array
arr1 = np.array([1, 2, 3])

# 2D Array
arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# 3D Array
arr3 = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print("ndim:", arr1.ndim)

print("ndim:", arr2.ndim)

print("ndim:", arr3.ndim)

ndim: 1
ndim: 2
ndim: 3


In [27]:
#shape
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr.shape)

(2, 3)


In [28]:
#value error ,unequal lengths of rows
arr = np.array([
    [1, 2, 3],
    [4, 5]
])

print(arr)
print(arr.shape)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.