In [1]:
import numpy as np

In [2]:
#Random numbers are usefulfor simulations, modeling, randomized algorithms,testing,
#and applying random transformations to data.


In [3]:
#rng => random number generator

In [4]:
#rng=np.random.default_rng()
#crated a random number genrator object

In [8]:
rng=np.random.default_rng()
#(low,high)=>generate a random numebr in between low and high(excluding high)
rng.integers(1,7)

np.int64(3)

In [10]:
#die formula
#generate one form six
rng.integers(1,7)

np.int64(1)

In [14]:
#size  used to control how many numbers are genrated and also the shape
rng.integers(1,100,3)
#(1,100,3)=>(low,high,size) it denotes 3 numebrs shold be randomly generated
rng.integers(1,50,5)# 5 integers

array([37,  2, 29, 49, 15])

In [16]:
#shape of the randomly generated numbers
rng.integers(1, 101, size=(3, 2))#3 rows and 2 columns

array([[68, 82],
       [17, 82],
       [68, 62]])

In [30]:

# ============================================================
# RANDOM NUMBERS IN NUMPY
# ============================================================

# ------------------------------------------------------------
# 1. Seeding for Reproducibility
# ------------------------------------------------------------
# Same seed → same random numbers every time
# Similar to a Minecraft world seed:
# Same seed → same world
#
# default_rng() is the recommended modern approach.

rng = np.random.default_rng(seed=1)

print("Random numbers:")
print(rng.random(5))




Random numbers:
[0.51182162 0.9504637  0.14415961 0.94864945 0.31183145]


In [31]:
# ------------------------------------------------------------
# 2. Uniform Random Floats
# ------------------------------------------------------------
# rng.uniform() → random float between 0 and 1
# Range: [0, 1)
#
# low = starting value
# high = ending value

print("\nRandom float (0 to 1):")
print(rng.uniform())

print("\nRandom float (-1 to 1):")
print(rng.uniform(low=-1, high=1))


# Generate 3 random floats
print("\n3 Random floats:")
print(rng.uniform(low=-1, high=1, size=3))


# Generate a 3 × 2 array
print("\n3 × 2 Random array:")
print(rng.uniform(low=-1, high=1, size=(3, 2)))





Random float (0 to 1):
0.42332644897257565

Random float (-1 to 1):
0.6554051876408835

3 Random floats:
[-0.18160173  0.09918738 -0.94488177]

3 × 2 Random array:
[[ 0.50702622  0.07628663]
 [-0.34053657  0.57685741]
 [-0.39361034 -0.09300422]]


In [26]:
# ------------------------------------------------------------
# 3. Shuffling
# ------------------------------------------------------------
# shuffle() randomly reorders an array IN PLACE
# → Original array itself gets changed

numbers = np.array([1, 2, 3, 4, 5])

print("\nBefore shuffle:")
print(numbers)

rng.shuffle(numbers)

print("After shuffle:")
print(numbers)


# For a 2D array:
# shuffle() reorders rows (first axis)

matrix = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

print("\nBefore 2D shuffle:")
print(matrix)

rng.shuffle(matrix)

print("After 2D shuffle:")
print(matrix)





Before shuffle:
[1 2 3 4 5]
After shuffle:
[1 3 5 2 4]

Before 2D shuffle:
[[1 2]
 [3 4]
 [5 6]]
After 2D shuffle:
[[5 6]
 [1 2]
 [3 4]]


In [27]:
# ------------------------------------------------------------
# 4. Random Choice
# ------------------------------------------------------------
# choice() randomly selects elements from an array
#
# replace=True  → element can be selected again
# replace=False → once selected, cannot be selected again

fruits = np.array([
    "apple",
    "orange",
    "banana",
    "coconut",
    "pineapple"
])

print("\nRandom fruit:")
print(rng.choice(fruits))


# Select 3 fruits
print("\n3 Random fruits (replace=True):")
print(rng.choice(fruits, size=3, replace=True))

#replace=True =>can select same element again and again
#replace=False=>can't select same element twice
# Select 3 different fruits
print("\n3 Random fruits (replace=False):")
print(rng.choice(fruits, size=3, replace=False))





Random fruit:
banana

3 Random fruits (replace=True):
['orange' 'apple' 'coconut']

3 Random fruits (replace=False):
['banana' 'apple' 'orange']


In [28]:
# ------------------------------------------------------------
# 5. 2D Random Choice
# ------------------------------------------------------------
# size=(3,3) → creates a 3 × 3 array

print("\n3 × 3 Random fruits:")
print(rng.choice(fruits, size=(3, 3)))





3 × 3 Random fruits:
[['pineapple' 'coconut' 'pineapple']
 ['apple' 'coconut' 'orange']
 ['banana' 'pineapple' 'orange']]


In [29]:
# ============================================================
# QUICK REVISION
# ============================================================
# np.random.default_rng(seed)
# → creates a random number generator
#
# Same seed → same random sequence
#
# rng.uniform(low, high, size)
# → random floating-point numbers
#
# rng.shuffle(array)
# → randomly reorders the array IN PLACE
# → 2D: shuffles rows
#
# rng.choice(array, size, replace)
# → randomly selects elements
#
# replace=True
# → repetition allowed
#
# replace=False
# → no repetition
#
# Modern approach:
# np.random.default_rng()
#
# Older approach:
# np.random.seed()
# ============================================================