In [1]:
import numpy as np

# Create a 4x4 NumPy array
array = np.array([
    [1,  2,  3,  4],
    [5,  6,  7,  8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

print("Original Array:")
print(array)


# -----------------------------------
# 1. Selecting individual rows
# -----------------------------------

print("\n--- Individual Rows ---")

print("First row:")
print(array[0])

print("Second row:")
print(array[1])

print("Last row:")
print(array[-1])

print("Second-last row:")
print(array[-2])


Original Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

--- Individual Rows ---
First row:
[1 2 3 4]
Second row:
[5 6 7 8]
Last row:
[13 14 15 16]
Second-last row:
[ 9 10 11 12]


In [2]:

# -----------------------------------
# 2. Row slicing
# -----------------------------------

print("\n--- Row Slicing ---")

print("Rows 0 to 2:")
print(array[0:3])

print("Rows 1 to end:")
print(array[1:])

print("Every second row:")
print(array[::2])

print("Rows in reverse:")
print(array[::-1])

print("Every second row in reverse:")
print(array[::-2])




--- Row Slicing ---
Rows 0 to 2:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Rows 1 to end:
[[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Every second row:
[[ 1  2  3  4]
 [ 9 10 11 12]]
Rows in reverse:
[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
Every second row in reverse:
[[13 14 15 16]
 [ 5  6  7  8]]


In [3]:

# -----------------------------------
# 3. Selecting columns
# -----------------------------------

print("\n--- Column Selection ---")

print("First column:")
print(array[:, 0])

print("Second column:")
print(array[:, 1])

print("Last column:")
print(array[:, -1])

print("Second-last column:")
print(array[:, -2])





--- Column Selection ---
First column:
[ 1  5  9 13]
Second column:
[ 2  6 10 14]
Last column:
[ 4  8 12 16]
Second-last column:
[ 3  7 11 15]


In [4]:
# -----------------------------------
# 4. Column slicing
# -----------------------------------

print("\n--- Column Slicing ---")

print("First three columns:")
print(array[:, 0:3])

print("Column 1 onwards:")
print(array[:, 1:])

print("Every second column:")
print(array[:, ::2])

print("Columns 1 and 3:")
print(array[:, 1::2])

print("Columns in reverse:")
print(array[:, ::-1])

print("Every second column in reverse:")
print(array[:, ::-2])





--- Column Slicing ---
First three columns:
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]
Column 1 onwards:
[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]
 [14 15 16]]
Every second column:
[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]
Columns 1 and 3:
[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]]
Columns in reverse:
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]
Every second column in reverse:
[[ 4  2]
 [ 8  6]
 [12 10]
 [16 14]]


In [5]:
# -----------------------------------
# 5. Selecting quadrants
# -----------------------------------

print("\n--- 2x2 Quadrants ---")

print("Top-left:")
print(array[0:2, 0:2])

print("Top-right:")
print(array[0:2, 2:])

print("Bottom-left:")
print(array[2:, 0:2])

print("Bottom-right:")
print(array[2:, 2:])


--- 2x2 Quadrants ---
Top-left:
[[1 2]
 [5 6]]
Top-right:
[[3 4]
 [7 8]]
Bottom-left:
[[ 9 10]
 [13 14]]
Bottom-right:
[[11 12]
 [15 16]]


In [8]:
import numpy as np
#start:stop:step
# we start from 1 and jump two step i.e to 3 then to 5 then 7
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])

print(arr[1:8:2])

[20 40 60 80]
